apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment # TODO: Add a unique name 
spec:
  replicas: 4 # TODO: Adjust the replica count as desired
  selector:
    matchLabels:
      app: flask-backend
  template:
    metadata:
      labels:
        app: flask-backend
    spec:
      containers:
      - name: flask-backend
        # TODO: Replace <your-dockerhub-username> with your Docker Hub username
        image: udedhia/backend-image-name:1.0.0
        ports:
        - containerPort: 5001
